import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "@/Components/Navber";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js first projects ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navber/>
        <div> {children}</div>
        <div className="flex justify-center h-20 items-center">@All write reserved by Habib ulla 2024
        </div>
      </body>
    </html>
  );
}
